listen: ':3000'
database:
  dsn: host=localhost user=postgres password= dbname=weplanx port=5432 sslmode=disable TimeZone=Asia/Shanghai
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  table_prefix:
