listen: ':5000'
database:
  dsn: root:pass@tcp(localhost:3306)/weplanx?charset=utf8mb4&parseTime=True&loc=Local
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  table_prefix:
auth:
  key:
  issuer: weplanx
  audience: [ console ]
  not_before: 0
  expires: 3600
